name: integration
on:
  push:
    branches:
    - master
    - author
jobs:
  test:
    runs-on: macOS-latest
    steps:
    - name: setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.x
    - name: checkout
      uses: actions/checkout@v1
    - name: install
      run: |
        GOBIN=$HOME/bin make install
        brew install mercurial fossil bazaar
    - name: test
      run: PATH=$HOME/bin:$PATH ./misc/author/integration_test.sh
